### ISSUE TITLE
can a POST be used to trigger a remote button instead of a GET?

### ISSUE THREAD

**Issue by mph070770** [alexbain/lirc_web#15]
Hi.
I want to be able to put my remote commands into another program that expects POST's instead of GET's for the URL's I supply, so:

POST http://192.168.0.55:3123/remotes/SKY/KEY_PAUSE

Is it possible to adapt your code to achieve this?

Thanks

**Comment by maddox** [comment]
@mph070770 What software is it? If it's [amazon-echo-ha-bridge](https://github.com/armzilla/amazon-echo-ha-bridge) :wink:, then it supports POST just fine.

It's not available via their configurator, but it DOES support it. Check out the docs on the [README](https://github.com/armzilla/amazon-echo-ha-bridge#postput-rest-api). You'll have to add your command yourself via the API.

**Comment by mph070770** [comment]
@maddox , good guess :-) but not quite. It was this:

https://github.com/makermusings/fauxmo

but I have also been trying amazon-echo-ha-bridge. I'll look at that in the mean time....

Thanks

**Comment by maddox** [comment]
I'm confused.You said you needed `POST`, `lirc_web` uses `POST` for commands.

**Comment by mph070770** [comment]
When I use the lirc_web page, it shows this on the console:

"POST /remotes/SKY/KEY_PAUSE HTTP/1.1" 200 - "http://192.168.0.55:3123/" "Mozilla/5.0 

When I try the same from fauxmo, it produces the following:

"GET /remotes/SKY/KEY_PAUSE HTTP/1.1" 404 - "-" "

I'm assuming this means that a GET is being issued by fauxmo. Perhaps I should also look to see if that can be changed....

**Comment by maddox** [comment]
Sorry, in your original post you said that the program expected `POST` and not `GET`.

According to those logs, yeah, fauxmo is using `GET` to make those calls. You'd probably have better luck asking that project to use `POST` instead. (It's the more semantically correct HTTP verb anyways.)

The other thing you could do is just change the code yourself on your checked out version. This isn't ideal, but you'll get what you want right away. When you set up `lirc_web`, just edit the code so that it accepts `GET` instead of `POST`. Or even better, fork it and you'll have your own maintained version.

Just change [this line](https://github.com/alexbain/lirc_web/blob/master/app.js#L95-L99):

```diff
-app.post('/remotes/:remote/:command', function(req, res) {
+app.get('/remotes/:remote/:command', function(req, res) {
```

**Comment by mph070770** [comment]
Yes, understood, sorry for the confusion and thanks for your help. It looks like I have a couple of options to get me going - I'll have a look. Thanks again.

**Comment by maddox** [comment]
np!

**Comment by alexbain** [comment]
Glad you guys got it sorted out, closing this.
