### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by jsavage** [alexbain/lirc_web#55]
Have cloned repo and edited config.json but am getting an error:

```
[SyntaxError: /home/pi/.lirc_web_config.json: Unexpected token }]
WARNING: Cannot find config.json!
```

FWIW my config follows.  Grateful if anyone can work out what might be causing the issue.

```
{
  "server" : {
    "port" : 3000,
    "ssl" : false,
    "ssl_cert" : "/home/pi/lirc_web/server.cert",
    "ssl_key" : "/home/pi/lirc_web/server.key",
    "ssl_port" : 3001
  },
  "repeaters": {
    "sharp-LCDTV-RC4847": {
      "KEY_VOLUMEUP": true,
      "KEY_VOLUMEDOWN": true
    }
  },
  "macros": {
    "TestMacro": [
      [ "sharp-LCDTV-RC4847", "KEY_1" ],
      [ "sharp-LCDTV-RC4847", "KEY_1" ],
      [ "sharp-LCDTV-RC4847", "KEY_1" ]
    ]
  },
  "commandLabels": {
    "sharp-LCDTV-RC4847": {
      "KEY_VOLUMEUP": "Volume Up",
      "KEY_VOLUMEDOWN": "Volume Down"
    }
  },
  "remoteLabels": {
     "sharp-LCDTV-RC4847": "TV"
  },
  "blacklists": {
     "sharp-LCDTV-RC4847": [
       "KEY_BLUE",
       "KEY_GREEN"
     ]
  }
}
```

**Comment by flochtililoch** [comment]
According to the error you posted, it looks like:
- the `config.json` file at the root of your `lirc_web` local copy is either missing or contains an error.
- because of that, the `/home/pi/.lirc_web_config.json` is read instead, but contains an error (`Unexpected token }`)

Where is your `config.json` file located?
You can probably delete `/home/pi/.lirc_web_config.json` if you are using `config.json` instead.
See details of how configuration works in the [README](https://github.com/alexbain/lirc_web#configuration)

**Comment by jsavage** [comment]
Thanks - You were right. I was looking in the wrong place. It was a stray .lirc_web_config that was causing the issue and the above config was fine.
